[target.x86_64-unknown-linux-musl]
#image = "ghcr.io/caddijp/rust-musl-builder/rust-musl-builder:1.55.0"
image = "rustembedded/cross:x86_64-unknown-linux-musl-0.1.16"

[target.aarch64-unknown-linux-musl]
#image = "ghcr.io/caddijp/rust-musl-builder/rust-musl-builder:1.55.0"
image = "rustembedded/cross:aarch64-unknown-linux-musl-0.1.16"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG"
]